=== balmacefa/nft-engine/src/plugins/nft-engine/server/Schemas/CreateNFT.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "A JSON schema for: Create NFT in one API call",
  "properties": {
    "uploadIpfsFiles": {
      "type": "array",
      "description": "A collection of base64 data to be uploaded to the IPFS. Also, assign each file result to the NFT Metadata Path.",
      "items": [
        {
          "type": "object",
          "properties": {
            "base64data": {
              "type": "string",
              "description": "Base 64 data will be uploaded to the IPFS."
            },
            "setMetadataPath": {
              "type": "string",
              "description": "The upload result will be set to JSON NFT Metadata obj, specify by this Path, which is done internally by  [lodash _.set](https://lodash.com/docs/4.17.15#set)"
            }
          },
          "additionalProperties": false,
          "required": [
            "base64data",
            "setMetadataPath"
          ]
        }
      ],
      "additionalItems": true
    },
    "nftMintOrder": {
      "type": "object",
      "description": "This defines the NFT Collection - Blockchain, collection name, royalties, symbol, and the Unique NFT Token id; this information is used to identify the order in the system.",
      "properties": {
        "sendAddress": {
          "type": "string",
          "description": "During the Mint phase, the NFT will be sent to this address. This will be the NFT's owner."
        },
        "blockchain": {
          "type": "string",
          "description": "At the moment, only Polygon MATIC is supported. Other blockchains will be integrated in the future ( BSC, CELO, ONE).",
          "enum": [
            "MATIC"
          ]
        },
        "tokenId": {
          "type": "string",
          "description": "Token ID that will be issued. This identifies the NFT within the collection.",
          "pattern": "^[0-9]{1,32}$"
        },
        "collectionName": {
          "type": "string",
          "description": "Name of the collection"
        },
        "symbol": {
          "type": "string",
          "description": "The collection's symbol. For example, the Bitcoin symbol is BTC.",
          "pattern": "^[a-zA-Z0-9_-]{1,30}$"
        },
        "royalties": {
          "type": "array",
          "description": "At the moment, Opensea does not support split revenue. When a splitter address is implemented or our NFT Marketplace contract becomes accessible, this information will be used. This project will earn a split revenue of 2.5%.",
          "items": [
            {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string",
                  "description": "Address where royalties should be sent every transaction"
                },
                "splitRoyaltyRate": {
                  "type": "number",
                  "description": "Percentage for this Address"
                }
              },
              "additionalProperties": false,
              "required": [
                "address",
                "splitRoyaltyRate"
              ]
            }
          ],
          "additionalItems": true
        }
      },
      "additionalProperties": false,
      "required": [
        "sendAddress",
        "blockchain",
        "tokenId",
        "collectionName",
        "symbol"
      ]
    },
    "nftMetadata": {
      "type": "object",
      "description": "NFT JSON Metadata, This can be a NFT standard or any other structure that fits your business logic. For Opensea or marketplace standard see https://docs.opensea.io/docs/metadata-standards",
      "additionalProperties": true
    },
    "webhooks": {
      "type": "object",
      "description": "Webhook for each stage of the redis job status - For further information and structure, see the Webhooks Section.",
      "properties": {
        "completed": {
          "type": "string",
          "description": "This is triggered when the NFT is successfully minted."
        },
        "progress": {
          "type": "string",
          "description": "This is triggered when job update the status of the order/job"
        },
        "failed": {
          "type": "string",
          "description": "This is triggered when a task fails. Please keep in mind that the job is retrying 10 times until the order's status is declared as unrecoverable. Fatal Error"
        },
        "unrecoverableFatalError": {
          "type": "string",
          "description": "This is triggered when a job fails many times and will not be retried; the job is then removed from the queue stack."
        }
      },
      "additionalProperties": false,
      "required": [
        "completed"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "nftMintOrder",
    "nftMetadata"
  ]
}

=== balmacefa/nft-engine/src/plugins/nft-engine/server/payloads/CreateNFT.json
{
  "nftMintOrder": {
    "sendAddress": "0xf2b5b9e978ee841c2b1507a09aa715d19f0d76fc",
    "blockchain": "MATIC",
    "tokenId": "1",
    "collectionName": "Prosperity_symbols",
    "symbol": "ProsperSymbol",
    "royalties": [
      {
        "address": "0x1837F49559fC820f28C1C239aDF53854dba570Ba",
        "splitRoyaltyRate": 10
      }
    ]
  },
  "nftMetadata": {
    "description": "The Jin Chan is a mythical creature that is said to appear during the full moon, near houses or businesses that will soon receive good news. Most of the time, the nature of this good news is understood to be wealth-related.  According to feng shui beliefs, Jin Chan helps attract and protect wealth, and guards against bad luck.",
    "image": "This will be set by payload: uploadIpfsFiles[0].setMetadataPath",
    "name": "Jin Chan",
    "attributes": [
      {
        "trait_type": "Species",
        "value": "Toad"
      },
      {
        "trait_type": "Ability",
        "value": "Attracts and protects wealth, and guards against bad luck"
      },
      {
        "trait_type": "Weakness",
        "value": "Should never be kept in the bathroom, bedroom, dining room or kitchen"
      },
      {
        "display_type": "date",
        "trait_type": "birthday",
        "value": 1546360800
      }
    ],
    "custom_data": {
      "wikepedia": "https://en.wikipedia.org/wiki/Jin_Chan"
    }
  },
  "webhooks": {
    "completed": "https://your_domain.xyz/completed",
    "progress": "https://your_domain.xyz/progress",
    "failed": "https://your_domain.xyz/failed",
    "unrecoverableFatalError": "https://your_domain.xyz/unrecoverableFatalError"
  },
  "uploadIpfsFiles": [
    {
      "setMetadataPath": "image",
      "base64data": "/9j/4AAQSkZJRgABAQEAZABkAAD/2wCEAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSgBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/CABEIAeAB7gMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAEBQIDBgEHAAj/2gAIAQEAAAAA9s5Plt/Pp2dt7FohzM5fQnPk7PuwW0CR7z7vZElRpjZOcbiLOy+q79H6UKmsOysI5yy367sGiLMWS+737tnfuyGCHplCU2zcmeZCVBOvUMlR2VneRl9Hva6T+dlO7v1tnLpxaI8vbLvfuylzve5YfUOB04mdpvcFFz8lRut23dcj9KfY/RjKFJfO/dKl9Zby/smyDK2Ss73LPmgGsyvjecVq/TPVDPHBiyzDB3W5/MSD0PZaTQEwjP77n1f30J20S6VZKy2N8pts9kbbLJ57wff+h4ilMiyGFMss9A9e8xHYEOTb++L6DVK0mi/QUq5c7Z9XX9KcgpTItlK3ln03GeyHZ2LMAsF9B2fkCVRgp6/vmtXr/o357qu0TNkmCx+oIcG/pP7k59+jGEJSkvQo6uR59VZ8PfULyBXnWCZ6RzuEXjyAh/pLM7hGXoSxMB0zR69mp0npivFe5Vc72UK+cr5PqXzSFNNf1c74VXTtfswfI8d3VL3WSxd3fRpBq8vCWq0fQdj7Bpby3CTzrEeu6uQUJcjyP0R78j5XQNCvtj7b5T5rmUorDS9qxgb2A/mSpxvc0EsjE/m81Gf91Gx9tuuaeXOHjn0fOfS72MIRDJ888NVUv/QuYn0xYdbidQg9aV4Hzsf2b1MTwdigxDk3Mrvj6hjBueg630fOZgTSaTM0HPNmS2792MIVg2YP89AaK04wEVu59B86PZjefY4P0DWGer/lVi+cK1YUla8lK4zj5kDtvQUufH2IU1dPrmoaRt+5Gv5VZjPztfu8HoVAOlQUbDSn4k3xddt97fNsr81bmE5dGNsZDdjkjvU8Mq1e+c5XutDYYrY6B3pbZdjXxNLI+BvGvkmheIGfcrVrw46HyYz2vMsmcyo58AO9kZiS6dNhI+haLFpTNsxbTASKHRhf3sJs+1/cz92R8N9FwuIhsEpVwNIn1PoPk+52Sek9tA22ziqNAwh8RHjMNIZDQZbJqsxR87NMd/qxvKf0fsz3J+J+reQ8x2oz+hXsFwVRW/8AOTdnCcjT4GL4iOCwk7ZkXWGDfk8pkl07PrCNGx9YC9D9GlZ2P2VjlfLd54or+GhvQM+6HRt9d5Mw9FYWwLJHt+Is6GFM26SHP4vLVkFfSJOm4aav1a5zsZifdliasjnvU/x8H9wo6rulAyT/AHfk92/r0B7Do9lwQvK76fPs2FRIU11fCBBrujN6L03SSkfrd8jrlhAPPCN/+ZgaVQTQ0ZrqcQ09P8cou7btdOxqmNQqsuxnnQtu0NCDlvdHmqWjC74tY+2m3I73RTztvn6LyR84xQypEghqxl7io7cpvPWar0V1DLEOymg+O8/BfaxtcdcUpB1vqLjPlCu755ZWS4j68F57oC/NlOaOXZIYVLnkuoNUaIEpP695tj32hUXPmF6PM5yGu2MFagKibI8n4ojU6du1ekzrESVJeehu5eXZfM4jF6m4SkFZLRWfM88l0PpePXOVebGurDHc6+ofhIZkZXOGJrGFKvrKRhhrNiydNbLO+ReerFeVYNF9IA6jTaNe3wFJUvQdCKvQ5nMF6LYj5ETSbRWMA3csmrVjQlVA3sbWRvp90foSvsj4z55ngPumXJxB1wezFYZcmJi4atgWbpGAGRXGkabQuq85kdC/dMmlCRbX9c6iy9UlGXPrux8WwIIWMfEEjcXLkJ+hRMu/DF1LLLT+8IZkyYNGbgrPIMM40Lom4YOhg+X1vPSiR6h48+h5/jUwC5zRG2BeWVqzLTXdFQy8pWWSZo9NxbbclBfb96pxWAYEWlFFEafDgOtk4MhCEY2Tw+bkFRQp+LYfLaF+fFOtZt+0Us5kP2pfMEh1XpZPkK7WbaWFp2FV0l1mSRb/AD+59DZzJsh9P78uZ5T9rBKhzqCla4dJz4twuZ7/AE9v1FUGqvzzMd13or1GjXwKNaWk/U0eK7L09AfuN9d2cIV9/MnnKr0g0LD+gNfOjVYi5bT2ZrCzQNmkTQ2E8jmxRi2+j2b00PhBirODNM55H6yf5d6B63nfR9L3lVdn5iRjbpavH3/nQNdByOAyoT6wxk8Ygs1oCfmh0kRQKu23F33SJflpPJ87pJZxn+uXmF9Ul3tffyl8r1NEsxuFqXtSxStiJGEJmPyxFa2snU6luzavbfl4ddNVNtaPA5El3B5qvU91PQLOy59+R0yumkATUemYKhJZJY5rXU9G++7DlhLp+wLObaRn8NUOEMIOixwV610609/o+8KVP6p28/G6LisCrlvoL5Hn2Gmy2dNqX2dGpjDvbWrgokkgkokj6scUFXnk2oKC12I2r875n7OZX2/n4ugKEvGOYPTluXZtESsqIEXcBVtf33bjjibSLibe1CjLaJ3OqrT32Jy7bWHet+pc52zn43+pWKAPUBNSu84H2Z2ZUtN7hs4LcWtr++++stvvunPsARR/jtG0JnPTWeVZmx/pNX7+07L6H5CI89D4f7Xl2TnzJb6syyfnDr0TJYYMgT7necndRL7n3L5/Cyh1lqm5rtd5gchtfUa/2v0eXfofkQ3yv6e1Y5NroMKLpnRPmzavZeWw79yPec+Iost+sP7Wp73v0plExZp9jjzvQs0H6T72xlDn5L553bf6OrxauwT5p6t5eqhx2rhKNf3ectrhayvvMSnoqbb77ih2VbVcfl9B6hkUDT3n0WfB/wAs2YWmWyIy6lbOITAGyQh/1ZHI095xgA2ahW2HxzsIAM23C4sWrvyl3ntN6UiL9edNO2UfmriDOpNDp6EANVgAxnFg5joeq37lRLAItOYVIyXXWUUzX6XZNGTAPxanXZXabRCx/RHe/Sq/PFK3PpwT9aQtoq+pT5+HIsnJVlpHyRLrV9Daiy02AmmxyK9ec+mwOFy2gV6baYVz+iDbfq4+C1LVwOBDbakmpKiorj9bD6ZN5PAF7vWIyZqRXTNjTdLA6FKkh96hrMwSjto9ATXe/NYQ+h4fxUnAyC8aRcwrrJiVkFVjEhXcHr0rihmoBGF2bKa175vqFeY4T73RnhwQVnoLoT3gyE/o+HdVZ7Pn48Sn5oJbOyF3PqCbkdkg/nGuDNFuQHavnVrjzb0XFZyOs9vz2WYJFyXXbor22mdkfvEZLMxi2RyNGLrGWdgX0mgc2/MVXR5HvpuYb3WVUtJRPzo1ynPh+jbtZjdQmrUstDvPXabL6afG+CY5Fky+BunDO5JR0c89flbraLaI0udrnjSayhbo7fAaDMJE0PRtCjwmy4xcaVvqtAcHbXV5DARHjFyU7RZ2kh85N+GXYtTdoRfuQDh17uFBA86GexwVceEKsdvNcjwWzs1bxk/fmv1P3KfIqB1Wcx1Oiy7Y4YcaIdYceFubyxVajpVxu4e2WX0YVivg/XhLKvacqqbpt07ZaBvc+FXQt8grGUrM3Xn59LJXTuykqHaRk7b9XKVvxFf1zV+vaW9GVmNKFJiX2LOyb4r1lkxdl2uGuRld5HRSsCBQ5U2FNt9egw4P1XzTeIShoXVD2oL9Yqo0/TM6qH1k6/lrvXAyM9CNNZkXM3+dWd8n5WKtCxS6aAPTXXusCCVRCfqmesEaAzpr4/zSq52YCGKl1pdkWkdeTLWsizTCL2LaeRj5dwccVd5zVNWsesHsfO67ejQe+gJKjL6Qg3zPzWq3XU1q6V+ibmpN8xNMOZmklFEFsL2ORX+b0VwEAwKrosLGczMFOdy2Vmj9GDUDQO0CTOoCF22LiPcG1Z1qvQyzD2rYmVxZTIjkl+e86qjUEJlsHZTb28sHOXzJVReqbdw/IpVZQAdvxNsHXxiCjSTT6XVFHMXhcvrDCzyavjsV5rXyIy9P5dwqQ/dL5yRIrVZDk9fk0042n6YSOlAV814hubvKoY+lEFHMmdvLbbSWRHYHqvG/oj0iKctlfod0mPU2TfP8d3rTQTFINnnYPj50CDOREldmh9AOtJOKKKiR2khwZZ90nwePafhVyZGFSNml3xN2yiLcSGvuNNjy01wR9T2Vpt82pV1915fbbp2dpKZnET5d4ZZV2uIShSsSYD6wkrQOuTJ7X9wb4hi2Nl99yM77C7iCirCrJWWT7ZC24w4m6VHidk+1xqBWALFGdAv0DmwgmcY2TsuKKvlLnedndOwgoi+y2c5S7Of0iySCr7JeJ/T+ElZUIGtCCojbeUTdOH3brLbyZXT+++lbKdsibbbJy79d3tdt95BJFpEfF+zhKE+UjjCV0V9stvuh2cZ9tnfZ2+XJznbGywnsrLI9s5OUbLLyibb5Xf/EABkBAAMBAQEAAAAAAAAAAAAAAAECAwQABf/aAAgBAhAAAADyC3BwteIHdNQbzjoOfl4k9zMSBTuQvl7UmDn2t5+qZ4HgHoCC/TlaT6jmM81N2Rl48OTtZbgEGmC6n8623OxgWAh3Dp10JylaBhTPrx7SYZIR46dC93Qu68qPbTn8zWsNrvz5s8GTbG57s9RszDQia/J6HVZq9Gdsldl0ViMzNrOZ7Zdnmrn4qWnbZquFgXVDic+gZIuf0M2XCHs3o2BxVRnu1IwyW5dhEpjVhE21Pl4SN62dJTGnHesK3yT25oLutGSxacp9WiWu7nHZ89LtF+LwzF4ZNFMsn1KmrWeOdl6PbaxkxTNmtJ5jXJTVabmIzWzui679HN5yOfR7zgeFe2Zb21HvPKi0qXsZ4Wt3nRIJbvRtOK7a9kuThstuoSyYc0ZK1K72SErbqdirfJm35dUdBZwkZotbLER9CeT0X7z964oeh5utbaiD3BQ5TLKtUmdp87bmOh8uhl7jwmsnt01kaZNb3PlV0ZHej1SK8yskRXVnyjdPHt1P3jPr0Zms3cqnsvaIQGuz+XVs99rnxH01vnqBy24YDyRpfSmHVyR17O8OmuqJnLXsOfLFWhWl+hpz4519w+FW72iz26ea2icciUsGbNRcUz7l/Dauihn2o4iQ3d06vJIHPEHf63gF9rtlroI809x2pKozjMig2Ps+EabK9HSZss1NJNI0jmmo43G7zS1rmt4QrFELKykQVVJ6tOiCdF9EspICzHEBB3AcXq0RxLllUjkHdy8O7u7i1af/xAAaAQADAQEBAQAAAAAAAAAAAAABAgMABAUG/9oACAEDEAAAAOo4FcSNts7DLmUODsMhy7YNsyr07np1hOfXiNtsDkxCvjeNXiG1ayhf0fGGxGaeBBcLdZj63g+fpscpRyMGOZcGmcZ9UOzmmtLVqh54DbFnIfTmlu3krWCKu6HoNzNzrsztOzRLQ7mqqhUzVnacIuktqkgVWd+btahwGpLn55k1mEYWwXOxpydFekqi8sWW+xEpJqVzVgBVtHpLrBehsyxSaUbCNsvQsug813bmlSuqHdxObwgqa5FRNaqAtegI/SiUdZB+KCkWZtbQk7FWvdHVjFsF0OQBriivSPNr36Tjy7qwBVI35oRx6WYTvNJB+nI3TTDKNyycaCDqVR0BkVVVX7rOSFnzq1NPkTdWnW/NeLyyy1Omh0pmiV53v5w3XA9HRx9kTPmADBsy5uppIaS5t2SoJraSVAXM1KLHUDMl+aUh25OhFVZPbMrA1Mo1s3G9+bmy9pSPQJLszhOho0qeeadii/Nyqe4okqrjmnh1BjaU4noi+PJI9wCM1RorgLsy0RJ55VoJ8Y70zTcJMUqsXtV5zKrRRXLxp3qMmpudenbAsryVqOMcsOf0FyDWnIbtAIgHC9CtiFmObuwni8GZWZhOivkZ9sFnp9QwBWNqI7HLgcDthtJdY4aaPYDMSBsdhtsEQWOw2JwxxwOGI22CIP/EAC0QAAICAgICAQQBBAMBAQEAAAECAwQAEQUSEyEQBhQiMSMVIDJBFiQzQjQw/9oACAEBAAEFARn+/gYMPyPgYcX/ACX/ABv5/wDX94+N/Dfp1wjCvvWa9EZrNZrAvtUOIMOHN6wH2M/1/tRg+APjWEZ1zrhXNZrDjDBrH/Y/WDFw/C/K5/oftf8AG9n/ANf/AMwMlXCMZc65421rOpxY2bK9LyMnGDP6OMk4v1PDJCxy5br1BX5uiRD9UcRE1fxXKtysILAXNYMGH418nB8HDn+2wfAOD5X5Hwv7X9Xc1+WDNfBzWAZojBhGBd4zLCkvOVOycvWY05ONuZYpPDj2KthhHGj2buSXyMF+TrHyUySpzEy4OZPWPlo5HtV3mh5Di5+Plr/Vd+oYvr+1EeN+szyEcN1rdoDNetfIGa+T8kfBw/G8GD9fC/K/Efsr+r2b/IZvB88nzENNvp6U2pOStiqIOSpTgpXdLlmGm3K8lLekMwjNzl1QRc44fifqqzWyr9V8ZeTkKDS17N6QPHKXHYaVziWETJLcPcyDdW88LPyUM1LkYYms/aSs/D1kpw07goSjn6ZyKeOXPWEfAzf9+vg/rfwMH6+B8j4i/Y/XIYf8h+vnnLhp0vFLNLwvLPxPI8zVPO16Eb1El5+R5rU7zyWW8eWrkYWSV2aLe3kaJYLgB4rk5Kk/av8AUUN6vcpyx8n1ReRh8SWYpWrzAKJPy7p2ebcfOSy+fhbguVq7fnzdlo0lsP8Ac17LJJGzPCT8b/sP9u8J9NitgYYHGvIueQYJVzzLrzJgnXPuFyOwm1sJ1v2E0Zl7CwufdJn3K5a5evAsv1LStSyCOvkLRyHgeTENjkOLNuO5xycXMrby15YhK8YeCBKuVpny0taytyo1d6c/gl4y74Z+Tkh5XjrU7LI0vdKs6pKnJHcHIN3S8gS3yUrWLcvmH81Oxx/JMxmna1yLyLNe4qvM99B0iOawDNZrNfJ+Tn+pm65Pb6BuQff9Rkw8jLn9Rk2OQlw8jLn382C9Nn3s2Nfm2nJWBkl6Vs8zZ5WzyPuJpDn1DXkV2X1QkDWpBp6E4DcdYpTv9bXitq3yZZDYaQQsK8XGwPg0uGcNksflM0LK/HXDAV5NUq3YIpx4S0ZhkTJDK+Vwzn7cS5xf0hyksbfRPMgS/TF+COj9OU2yhwvDQLyv0hwrVfo2OWrycKJYDxMjAZrB8n5I/svHqsspMnbC42XzvnbDJgcYJMaXA+8BzWL4xlVarr4a4DzRJnMy/cT2vPHlCuzTqSUhYxPTNbf1Bp3HXI07MJDJN2WKWV37d3zk2jE9n3IsHbIYWL1+/lWpNK39G5FWsUCtniOE8mcUtTiok56NGX6jj0OYhkyJoS3OTLUSDlikkn05Kr8bzPGwcVS5OpyBmh8ZPzrCM1mvjWJ8cvL0jab8jZXDZBP3Iz7kYLAONJ1Ti3oPJf4SsYLHC3kjqcRckWbi5kFqOWqTOSA08hq8nPXd6LzxccK3gjr1bsvKRKc4rhuX5OG99PXuNPDcc6y83GXms195IJOyQSK4VZI7l2KNzaYM8/kw9XYuTliXu5leWWvyX22Nz9ilkf1dysfIcbFw9yTl6X2zWW0yyBVjlIzjORZc5BvPE7DtxlzwSchyFmSb6dlqV7LWq8kYPb5GazWa+VOA+vqNtQyTkY1g4JWJ4uo1uVOLoJLLDQriEPYl4duPWH761BLxbyy36jWaLcles/dy89zPI1p7i05PoJl5Bvrjjw1mKz9vUu8jL4+DMkb8bSqwNwNiIXOThRr733ez3jnW/wAaCJuPkQ0X6BjWy2lZ5XVEiWOWRfBFAiR7lgRmknuSiKvaeGSw7y2+F49Io+w7cXyYtQ8vUNXNpIv3E0BoXoLJM5MdoLHJCmmvcgaVtb8d94QZo4VkjfNZr4I+DhGLh/XPjcF2PTJEWNfjmceUgrDOatSeds56Rnu1yyWuQsiSKjfYSTWuO5WPl6ctU8fyUdaP6o4yvYofRjtSpc3zKS2DYcsZFMnCwAZ2JFay8T+f+p1LhcWK020r2CM8VebJuKG7fDzzj/jzrlrjK1aJ54YooaX3CWoTNV8YijswRwVYyM/p4mM07wQUrU8GUr3fKl8TLcoFQX6K1dA1K0bUfMLlVVaP6jjeOfjQWl4e5/HFbCgjQwfOsPwuH1nN/wDjyLFZeKXzTXJhXEN1YnsTN
